// src/models/mock.model.js
const Joi = require('joi');
const { v4: uuidv4 } = require('uuid'); // Still needed for generateMockData

const conditionSchema = Joi.object({
  // Use 'source' instead of 'type' as per earlier discussions for consistency
  source: Joi.string().valid('query', 'headers', 'body', 'params').required(),
  field: Joi.string().required(), // Renamed from 'key' for consistency with 'field' in condition.service.js
  value: Joi.any().required(), // Value can be anything
  operator: Joi.string().valid('equals', 'notEquals', 'includes', 'exists').default('equals') // Operators from condition.service.js
});

const mockSchema = Joi.object({
  // REMOVED: id: Joi.string().default(uuidv4), // ID is generated by controller
  path: Joi.string().pattern(/^\/[a-zA-Z0-9\-_/:]+$/).required(), // Added ':' for path parameters
  method: Joi.string().valid('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS').uppercase().required(), // Added more methods and uppercase
  // REMOVED: status: Joi.number().integer().min(100).max(599).default(200), // Status is part of the 'response' object
  queryParams: Joi.object().pattern(Joi.string(), Joi.string()).optional().default({}), // Use optional and default
  headers: Joi.object().pattern(Joi.string(), Joi.string()).optional().default({}), // Use optional and default
  // requestBody: Joi.alternatives().try(Joi.object(), Joi.array()).optional(), // This is typically for conditions, not the main mock payload
  response: Joi.object({
    status: Joi.number().integer().min(100).max(599).default(200), // Status moved inside response
    body: Joi.alternatives().try(Joi.object(), Joi.array(), Joi.string()).default(''), // Default to empty string
    headers: Joi.object().pattern(Joi.string(), Joi.string()).default({ 'Content-Type': 'application/json' }),
    latency: Joi.number().integer().min(0).default(0)
  }).required(),
  active: Joi.boolean().default(true),
  conditions: Joi.array().items(conditionSchema).default([]),
  // REMOVED: createdAt: Joi.date().default(Date.now), // Generated by controller
  // REMOVED: updatedAt: Joi.date().default(Date.now) // Generated by controller
});

// Update schema can inherit and make fields optional
const updateSchema = Joi.object({
  path: mockSchema.extract('path').optional(),
  method: mockSchema.extract('method').optional(),
  response: mockSchema.extract('response').optional(),
  active: mockSchema.extract('active').optional(),
  conditions: mockSchema.extract('conditions').optional(),
  queryParams: mockSchema.extract('queryParams').optional(),
  headers: mockSchema.extract('headers').optional()
}).min(1); // At least one field is required for an update


// Generate mock data for testing (this is separate and can keep uuidv4 directly)
const generateMockData = () => ({
  id: uuidv4(), // Keep uuidv4 here as this generates an actual mock object for tests
  path: '/api/users',
  method: 'GET',
  response: { // Status is now inside response
    status: 200,
    body: {
      users: [
        { id: '{{faker.uuid}}', name: 'John Doe' },
        { id: '{{faker.uuid}}', name: 'Jane Smith' }
      ]
    },
    headers: { 'Content-Type': 'application/json' },
    latency: 300
  },
  active: true,
  createdAt: new Date().toISOString(), // Use ISOString for consistency
  updatedAt: new Date().toISOString() // Use ISOString for consistency
});

module.exports = {
  mockSchema,
  updateSchema,
  generateMockData
};